var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,d){if(b==Array.prototype||b==Object.prototype)return b;b[f]=d.value;return b};
$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var f=0;f<b.length;++f){var d=b[f];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,f){var d=$jscomp.propertyToPolyfillSymbol[f];if(null==d)return b[f];d=b[d];return void 0!==d?d:b[f]};$jscomp.polyfill=function(b,f,d,g){f&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,f,d,g):$jscomp.polyfillUnisolated(b,f,d,g))};
$jscomp.polyfillUnisolated=function(b,f,d,g){d=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var a=b[g];if(!(a in d))return;d=d[a]}b=b[b.length-1];g=d[b];f=f(g);f!=g&&null!=f&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:f})};
$jscomp.polyfillIsolated=function(b,f,d,g){var a=b.split(".");b=1===a.length;g=a[0];g=!b&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var c=0;c<a.length-1;c++){var e=a[c];if(!(e in g))return;g=g[e]}a=a[a.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?g[a]:null;f=f(d);null!=f&&(b?$jscomp.defineProperty($jscomp.polyfills,a,{configurable:!0,writable:!0,value:f}):f!==d&&($jscomp.propertyToPolyfillSymbol[a]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(a):$jscomp.POLYFILL_PREFIX+a,a=
$jscomp.propertyToPolyfillSymbol[a],$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:f})))};$jscomp.polyfill("Object.is",function(b){return b?b:function(f,d){return f===d?0!==f||1/f===1/d:f!==f&&d!==d}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(f,d){var g=this;g instanceof String&&(g=String(g));var a=g.length;d=d||0;for(0>d&&(d=Math.max(d+a,0));d<a;d++){var c=g[d];if(c===f||Object.is(c,f))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,f,d){if(null==b)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(f,d){return-1!==$jscomp.checkStringArgs(this,f,"includes").indexOf(f,d||0)}},"es6","es3");
(function(){var b=function(a,c){this.loader=a;this.rootEl=document.getElementById(c);this.rootEl.className+=" ih_loader";this.TotalFilesCount=this.LoadedFilesCount=this.TotalSize=this.LoadedSize=this.Percent=0;this.StatusText="Loading&hellip;"};b.prototype={Render:function(){var a=this.StatusText;0<this.LoadedSize&&0<this.TotalSize&&(a+=" ("+this._FormatSize(this.LoadedSize)+" of "+this._FormatSize(this.TotalSize)+")");0<this.LoadedFilesCount&&0<this.TotalFilesCount&&(a+=" ("+this.LoadedFilesCount+
" of "+this.TotalFilesCount+" files)");this.rootEl.innerHTML='<div class="ih_loader_container"><div class="status">'+a+'</div><div class="progress"><div style="width: '+Math.min(100,this.Percent)+'%;"></div></div></div>'},Destroy:function(){this.rootEl.innerHTML="";this.rootEl.className=this.rootEl.className.replace("ih_loader","")},UpdateStatusText:function(a){this.StatusText=a;this.Render()},_SizeRound:function(a,c){c=c||2;var e=Math.pow(10,c);a=Math.round(a*e)/e;a=a.toString();-1===a.indexOf(".")&&
(a+=".");e=/[0-9]+\.([0-9]*)/.exec(a);if(null!==e&&e[1].length<c)for(e=e[1].length;e<c;e++)a+="0";return a},_FormatSize:function(a){a=parseFloat(a);return 1048576<=a?this._SizeRound(a/1048576)+" Mb":1024<=a?this._SizeRound(a/1024)+" Kb":a+" Bytes"}};var f=function(a,c){this.Url=a;this.Method=c?c.toUpperCase():"GET";this.IsLoaded=!1;this.Data=null;this.StatusData={LastModified:null,LoadedLength:0,TotalLength:0};this.onprogress=this.onload=null;a=/\.([0-9a-z]+)(?:[\?#]|$)/i.exec(a);this.FileExtension=
null!==a?a[1]:null};f._CorsSupport="undefined"!==typeof window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest;f.prototype={_HaveUrlCors:function(){return 0!==this.Url.indexOf(window.location.protocol+"//"+window.location.hostname+(""==window.location.port?"":":"+window.location.port)+"/")},Load:function(){if(!this._HaveUrlCors()||f._CorsSupport)this.LoadByXhr();else if("HEAD"===this.Method){this.Data="";this.IsLoaded=!0;var a=this;setTimeout(function(){if("function"===typeof a.onload)a.onload(a.Data,
"")})}else switch(this.FileExtension){case "js":this.LoadByScriptElement();break;case "css":this.LoadByLinkElement();break;default:throw Error("Cannot load file `"+this.Url+"` with out CORS support.");}},LoadByScriptElement:function(){var a=this,c=document.createElement("script");c.async=!1;c.src=this.Url;c.onload=c.onerror=function(){if(!a.IsLoaded&&(a.Data="",a.IsLoaded=!0,"function"===typeof a.onload))a.onload(a.Data,"")};c.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==
this.readyState)setTimeout(function(){if(!a.IsLoaded&&(a.IsLoaded=!0,a.Data="","function"===typeof a.onload))a.onload(a.Data,"")}),this.onreadystatechange=null};document.getElementsByTagName("head")[0].appendChild(c)},LoadByLinkElement:function(){var a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=this.Url;document.getElementsByTagName("head")[0].appendChild(a);var c="sheet"in a?"sheet":"styleSheet",e=this,h=1E4,k=setInterval(function(){if(a&&a[c]){if(e.Data="",e.IsLoaded=
!0,clearInterval(k),"function"===typeof e.onload)e.onload(e.Data,"")}else if(h-=10,0>h&&(clearInterval(k),"function"===typeof e.onload))e.onload(e.Data,"Error")},10)},LoadByXhr:function(){var a=this,c=this._GetHttpRequest();c.onreadystatechange=function(e){if(this.readyState===("HEAD"===a.Method?2:4)){200===this.status&&(a.IsLoaded=!0,a.Data=this.responseText);try{var h=c.getResponseHeader("content-length")}catch(k){h=0}null!==h&&(a.StatusData.TotalLength=parseInt(h),a.StatusData.LoadedLength=parseInt(h));
a.StatusData.LastModified=c.getResponseHeader("last-modified")||null;if("function"===typeof a.onprogress)a.onprogress();if(a.IsLoaded&&"function"===typeof a.onload)a.onload(a.Data,this.status+": "+this.statusText)}};c.onprogress=function(e){a.StatusData.LoadedLength=e.loaded;if("function"===typeof a.onprogress)a.onprogress()};c.onerror=function(e){f._CorsSupport=!1;a.Load()};c.open(this.Method,this.Url,!0);c.send()},_GetHttpRequest:function(){if(window.XMLHttpRequest)return new XMLHttpRequest;if(window.ActiveXObject)return new ActiveXObject("MsXml2.XmlHttp")}};
var d=function(a,c){this._UrlList=a;this._Method=c||null;this.IsLoaded=!1;this.Items=[];this._HasError=!1;this.onprogress=this.onloadall=this.onerror=this.onload=null;this._Init()};d.prototype={_Init:function(){for(var a=this,c=0,e=this._UrlList.length;c<e;c++){var h=new f(this._UrlList[c],this._Method);h.onload=function(k,l){null===k?a._ErrorItemHandler(l):a._LoadItemHandler()};h.onprogress=function(){a._ProcessItemHandler()};this.Items.push(h)}},_ErrorItemHandler:function(a){this._HasError=!0;if("function"===
typeof this.onerror)this.onerror(this,a)},_LoadItemHandler:function(){if(!this._HasError){if("function"===typeof this.onload)this.onload(this);for(var a=!0,c=0,e=this.Items.length;c<e;c++)a=a&&this.Items[c].IsLoaded;if(!this.IsLoaded&&!0===a&&(this.IsLoaded=!0,"function"===typeof this.onloadall))this.onloadall(this)}},_ProcessItemHandler:function(){if(!this._HasError&&"function"===typeof this.onprogress)this.onprogress(this)},Load:function(){for(var a=0,c=this.Items.length;a<c;a++)this.Items[a].Load()}};
var g=function(a){this.BasePath=window.location.href.replace(window.location.hash,"").replace(/[^\/]+?$/,"");this.BasePath=a.BasePath=a.BasePath?this.GetFolderUrl(a.BasePath):this.BasePath;this.Settings=a;this.ThemeName=a.ThemeName=a.ThemeName||this.DEFAULT_THEME;this.IconsSize=a.IconsSize=a.IconsSize||this.DEFAULT_ICONS_SIZE;this.NoCache=a.NoCache=a.NoCache||!1;this.ThemesPath=a.ThemesPath=this.GetFolderUrl(a.ThemesPath||"themes");a.FileIconsPath=this.GetFolderUrl(a.FileIconsPath||"icons");a.MsOfficeTemplatesPath=
this.GetFolderUrl(a.MsOfficeTemplatesPath||"templates");a.PluginsPath=this.GetFolderUrl(a.PluginsPath||"plugins");a.Platform=a.Platform?a.Platform.toLowerCase():null;this.Platform=a.Platform&&a.Platform!==this.PLATFORM_AUTO?a.Platform:this._DetectPlatform();switch(this.Platform){case this.PLATFORM_DESKTOP:this.LibFiles=[this.GetFileUrl("ITHitAJAXFileBrowser.js"),this.GetThemeFileUrl("desktop.css"),this.GetThemeFileUrl("icons_"+this.IconsSize+".css")];break;case this.PLATFORM_MOBILE:case this.PLATFORM_TABLET:this.LibFiles=
[this.GetFileUrl("ITHitAJAXFileBrowserMobile.js"),this.GetThemeFileUrl("mobile.css")];break;default:throw Error("Wrong platform type `"+this.Platform+"`. Available types: `auto`, `desktop`, `tablet`, `mobile`.");}this._ContentItemsLoader=this._HeadItemsLoader=null;this._HasError=!1;this.UI=new b(this,a.Id)};g.prototype={DEFAULT_THEME:"windows_8",DEFAULT_ICONS_SIZE:16,PLATFORM_AUTO:"auto",PLATFORM_DESKTOP:"desktop",PLATFORM_TABLET:"tablet",PLATFORM_MOBILE:"mobile",CALCULATE_BY_SIZE:"size",CALCULATE_BY_FILES_COUNT:"files_count",
CALCULATE_BY_FILES_WHEN_IT_MORE:5,onload:null,oninit:null,LoadAsync:function(){var a=this,c=this.GetThemeFileUrl("loader.css"),e=new f(this._AppendTimeToUrl(c,(new Date).getTime()),"HEAD");e.onload=function(){var h=(new Date(e.StatusData.LastModified)).getTime();h=new f(a._AppendTimeToUrl(c,h));h.onload=function(k){a._InsertStyle(k);a.UI.Render();a._LoadLib()};h.Load()};e.Load()},GetFolderUrl:function(a){a=(a||"").replace(/\/+$/,"")+"/";return this.GetFileUrl(a)},GetFileUrl:function(a){a=a||"";return-1!==
a.indexOf("://")||0===a.indexOf("/")?a:this.BasePath+a},GetThemeFolderUrl:function(){return this.GetFolderUrl(this.ThemesPath+this.ThemeName)},GetThemeFileUrl:function(a){return this.GetFileUrl(this.ThemesPath+this.ThemeName+(a?"/"+a:""))},_LoadLib:function(){for(var a=this,c=[],e=0,h=this.LibFiles.length;e<h;e++)c.push(this._AppendTimeToUrl(this.LibFiles[e],(new Date).getTime()));this._HeadItemsLoader=new d(c,"HEAD");this._HeadItemsLoader.onerror=function(k,l){a.UI.UpdateStatusText(l)};this._HeadItemsLoader.onloadall=
function(){a._LoadLibContent()};this._HeadItemsLoader.Load()},_LoadLibContent:function(){for(var a=this,c=[],e=0,h=this.LibFiles.length;e<h;e++){var k=(new Date(this._HeadItemsLoader.Items[e].StatusData.LastModified)).getTime();c.push(this._AppendTimeToUrl(this.LibFiles[e],k))}this._ContentItemsLoader=new d(c,"GET");this._ContentItemsLoader.onerror=function(l,m){a.UI.UpdateStatusText(m)};this._ContentItemsLoader.onprogress=function(){a._ProcessItemHandler()};this._ContentItemsLoader.onloadall=function(){a._AllLoadHandler()};
this._ContentItemsLoader.Load()},_AppendTimeToUrl:function(a,c){c=c.toString();c+="_"+encodeURIComponent(("https:"===window.location.protocol?"s":"")+window.location.hostname+window.location.port);return this._AppendUrlParam(a,"t",c)},_AppendUrlParam:function(a,c,e){return a+(-1==a.indexOf("?")?"?":"&")+encodeURIComponent(c)+"="+encodeURIComponent(e)},_ProcessItemHandler:function(){for(var a=0,c=0,e=0,h=this.LibFiles.length;e<h;e++){var k=this._HeadItemsLoader.Items[e];k.StatusData.TotalLength&&(a+=
this._ContentItemsLoader.Items[e].StatusData.LoadedLength,c+=k.StatusData.TotalLength)}this.UI.LoadedSize=a;this.UI.TotalSize=c;this.UI.Percent=Math.round(100*a/c);this.UI.Render()},_AllLoadHandler:function(){this.UI.Destroy();for(var a=0,c=this._ContentItemsLoader.Items.length;a<c;a++){var e=this._ContentItemsLoader.Items[a];switch(e.FileExtension){case "js":this._InsertJavaScript(e.Data);break;case "css":this._InsertStyle(e.Data);break;default:throw Error("Can not detect format for file `"+e.Url+
"`");}}if("function"===typeof this.onload)this.onload();var h=this.Platform===this.PLATFORM_DESKTOP?new ITHit.WebDAV.Client.AjaxFileBrowser.Controller(this.Settings):new ITHit.WebDAV.Client.AjaxFileBrowserMobile.Controller(this.Settings),k=this;ITHit.Events.AddListener(h,"OnInit",function(){if("function"===typeof k.oninit)k.oninit(h)})},_InsertJavaScript:function(a){if(a){var c=document.getElementsByTagName("HEAD").item(0),e=document.createElement("script");e.language="javascript";e.type="text/javascript";
e.id=this.SCRIPT_ID;e.defer=!0;e.text=a;c.appendChild(e)}},_InsertStyle:function(a){if(a){a=a.replace(/url\(('|")?([^'"d][^'")]+)('|")?\)?/g,"url("+this.GetThemeFolderUrl()+"$2)");var c=document.createElement("style");c.type="text/css";c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));document.getElementsByTagName("head")[0].appendChild(c)}},_DetectPlatform:function(){var a=navigator.userAgent.toLowerCase();if(/ipad/i.test(a))return this.PLATFORM_TABLET;if(/iphone|ipod|meego|webos|iemobile|opera mini/i.test(a))return this.PLATFORM_MOBILE;
if(/android/i.test(a))return/mobile/i.test(a)?this.PLATFORM_MOBILE:this.PLATFORM_TABLET;if(/blackberry|bb10|rim/i.test(a))return/tablet/i.test(a)?this.PLATFORM_TABLET:this.PLATFORM_MOBILE;if(/windows/i.test(a)){if(/phone/i.test(a))return this.PLATFORM_MOBILE;if(/touch/i.test(a))return this.PLATFORM_TABLET}if(/\(mobile;|\(tablet;|; rv:/i.test(a)){if(/mobile/i.test(a))return this.PLATFORM_MOBILE;if(/tablet/i.test(a))return this.PLATFORM_TABLET}return this.PLATFORM_DESKTOP}};this.ITHit=this.ITHit||{};
this.ITHit.WebDAV=this.ITHit.WebDAV||{};this.ITHit.WebDAV.Client=this.ITHit.WebDAV.Client||{};this.ITHit.WebDAV.Client.AjaxFileBrowserLoader=g;this.ITHit.WebDAV.Client.AjaxFileBrowser=this.ITHit.WebDAV.Client.AjaxFileBrowser||{};this.ITHit.WebDAV.Client.AjaxFileBrowser.Render=this.ITHit.WebDAV.Client.AjaxFileBrowser.Render||{};this.ITHit.WebDAV.Client.AjaxFileBrowser.Render.ViewModes={Details:"details",Medium:"medium",Large:"large",ExtraLarge:"extralarge"}})();var PERMISSION_READONLY=1,DAV_PATH_TOP="/ds/dav/",READONLY_INVISIBLE_SEPARATORS=[1,2,3],origin=window.location.origin,shared_id=window.location.hash.split(DAV_PATH_TOP)[1].split("/")[0],shared_dav_top=origin+DAV_PATH_TOP+shared_id+"/",dl_portal_url=origin+"/share/"+shared_id,api_url=origin+"/v2/api/share/public/"+shared_id,onResponseAlertStatus=[400,401],isOnResponseAlertShow=!0;function onOpenItem(b){if(b.ResourceType!=ITHit.WebDAV.Client.ResourceType.Folder)return window.open(b.Href),!1}
function onResponse(b){onResponseAlertStatus.includes(b.Status)&&isOnResponseAlertShow&&(isOnResponseAlertShow=!1,window.alert(ITHit.Phrases.AjaxFileBrowser.Teracloud.Share.Unauthorized),window.location=dl_portal_url)}
function getToolbar(b){settings=[{Id:"ViewsButton",contextHelp:!1,Show:!1},{Id:"FoldersButton",contextHelp:!1,Show:!1},{Id:"UpButton",contextHelp:!1},{Id:"RefreshButton",contextHelp:!1},{Id:"UploadButton",contextHelp:!1,Show:!b},{Id:"UploadFolderButton",Show:!1},{Id:"NewFolderButton",contextHelp:!1,Show:!b},{Id:"EditButton",Show:!1},{Id:"FileManagerButton",Show:!1},{Id:"VersionsButton",Show:!1},{Id:"CustomPropButton",Show:!1},{Id:"DeleteButton",Show:!b},{Id:"UndoButton",contextHelp:!1},{Id:"RedoButton",
contextHelp:!1},{Id:"CopyButton",Show:!b},{Id:"CutButton",Show:!b},{Id:"PasteButton",Show:!b},{Id:"LockButton",contextHelp:!1},{Id:"UnlockButton",contextHelp:!1}];b&&READONLY_INVISIBLE_SEPARATORS.forEach(function(f){settings.push({Id:"Separator"+f,show:!1})});return settings}var ajaxFileBrowser,isDesktop;
function onShowMenu(b,f){function d(g,a){a:{for(var c=0,e=g.Children.length;c<e;c++)if(g.Children[c].Id===a){a=c;break a}a=-1}-1!==a&&(g.Children.splice(a,1),0<a&&"MenuSeparator"===g.Children[a-1].Type&&g.Children.splice(a-1,1))}d(b,"UploadFolder");d(b,"NewDocument");d(b,"OpenFolderInFM");d(b,"View");d(b,"OpenDocument");d(b,"Edit");d(b,"EditDocument");d(b,"EditDocumentWith");d(b,"OpenContainingFolderInFM");d(b,"Versions");d(b,"CustomProperties");isReadonly&&(d(b,"NewFolder"),d(b,"UpdateFile"),d(b,
"UploadFile"),d(b,"Copy"),d(b,"Cut"),d(b,"Paste"),d(b,"Rename"),d(b,"Delete"))}
function InitAjaxFileBrowser(b){var f=shared_dav_top,d={};try{d=AjaxFileBrowserPhrases()}catch(a){}var g=getToolbar(b);f=new ITHit.WebDAV.Client.AjaxFileBrowserLoader({BasePath:"/sbrowser",Id:"AjaxFileBrowserContainer",Url:f,Style:"height: 100%; width: 100%",MsOfficeTemplatesPath:f+"/templates/",SelectedFolder:f,ThemeName:"teracloud",ThemesPath:"/browser/themes/",FileIconsPath:"/browser/icons/",SearchAutocompleteEnable:!1,SearchDynamicEnable:!1,Phrases:d,NotAllowedCharacters:"&?#\\<>+%",IconsSize:24,
Panels:{Folders:{Show:!1},AddressBar:{Show:!0},UploadPanel:{Show:!1},FilesView:{Columns:[{Id:"Icon",Show:!0,Width:"50px",CellStyles:{textAlign:"center"}},{Id:"Name",Show:!0,Width:"500px"},{Id:"Size",Show:!0,Width:"150px"},{Id:"Type",Show:!0,Width:"150px"},{Id:"DateModified",Show:!0,Width:"150px"}]},Toolbar:{Show:!0,Items:g},UploadProgressPanel:{Show:!b,Order:"Icon Source Destination ProgressBar Progress Uploaded FileSize Speed TimeLeft TimeElapsed".split(" "),Columns:[{Id:"Icon",Show:!0,Width:"30px",
CellStyles:{textAlign:"center"}},{Id:"Source",Show:!0,Width:"200px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"left"}},{Id:"Destination",Show:!0,Width:"200px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}},{Id:"ProgressBar",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"}},{Id:"Progress",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"left"}},{Id:"Uploaded",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}},
{Id:"FileSize",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}},{Id:"Speed",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}},{Id:"TimeLeft",Show:!0,Width:"80px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}},{Id:"TimeElapsed",Show:!0,Width:"100px",HeaderStyles:{textAlign:"left"},CellStyles:{textAlign:"right"}}]}}});isDesktop=f.Platform===f.PLATFORM_DESKTOP;f.oninit=function(a){ajaxFileBrowser=a;a=isDesktop?ajaxFileBrowser.GetSession():
ajaxFileBrowser.GetSession()._Session;ITHit.Events.AddListener(ajaxFileBrowser,"OnOpenItem",onOpenItem);ITHit.Events.AddListener(a,"OnResponse",onResponse);isDesktop?(ajaxFileBrowser.SetViewMode("details"),ajaxFileBrowser.SearchBar._Node.hidden=!0,ITHit.Events.AddListener(ajaxFileBrowser.GetMenuManager(),"OnShowMenu",onShowMenu)):(ajaxFileBrowser.SetViewMode("list"),ITHit.Components.jQuery('[data-role="header"] .button-viewmode-popup').hide(),ITHit.Components.jQuery('[data-role="header"] .button-editmode').hide(),
ITHit.Components.jQuery('[data-role="header"] .button-tree').hide(),ITHit.Components.jQuery('[data-role="header"] .ui-title').css("margin-left","50px"),b&&(ajaxFileBrowser.SetEditMode("view"),ITHit.Components.jQuery('[data-role="header"] .button-edit').hide()))};f.LoadAsync()}var isReadonly;
fetch(api_url).then(function(b){return b.json()}).then(function(b){isReadonly=b.permission===PERMISSION_READONLY;InitAjaxFileBrowser(isReadonly)}).catch(function(b){b=AjaxFileBrowserPhrases().AjaxFileBrowser.Teracloud.Share.Unauthorized;window.alert(b);window.location=dl_portal_url});
