var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,g){a instanceof String&&(a=String(a));for(var p=a.length,n=0;n<p;n++){var D=a[n];if(d.call(g,D,n,a))return{i:n,v:D}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,g){if(a==Array.prototype||a==Object.prototype)return a;a[d]=g.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var g=a[d];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,d){var g=$jscomp.propertyToPolyfillSymbol[d];if(null==g)return a[d];g=a[g];return void 0!==g?g:a[d]};
$jscomp.polyfill=function(a,d,g,p){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,g,p):$jscomp.polyfillUnisolated(a,d,g,p))};$jscomp.polyfillUnisolated=function(a,d,g,p){g=$jscomp.global;a=a.split(".");for(p=0;p<a.length-1;p++){var n=a[p];if(!(n in g))return;g=g[n]}a=a[a.length-1];p=g[a];d=d(p);d!=p&&null!=d&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,g,p){var n=a.split(".");a=1===n.length;p=n[0];p=!a&&p in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var D=0;D<n.length-1;D++){var A=n[D];if(!(A in p))return;p=p[A]}n=n[n.length-1];g=$jscomp.IS_SYMBOL_NATIVE&&"es6"===g?p[n]:null;d=d(g);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,n,{configurable:!0,writable:!0,value:d}):d!==g&&($jscomp.propertyToPolyfillSymbol[n]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(n):$jscomp.POLYFILL_PREFIX+n,n=
$jscomp.propertyToPolyfillSymbol[n],$jscomp.defineProperty(p,n,{configurable:!0,writable:!0,value:d})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(d,g){return $jscomp.findInternal(this,d,g).v}},"es6","es3");var API_TIMEOUT_MSEC=15E3,RESOURCETYPE_FILE=1,RESOURCETYPE_FOLDER=2,api_host=null;
angular.module("TeraCLOUDShare",["pascalprecht.translate","ngDialog"]).factory("$exceptionHandler",["$log",exceptionHandlerFactory]).config(["ngDialogProvider",ngDialogProviderConfig]).config(["$locationProvider",locationProviderConfig]).config(["$httpProvider",httpProviderConfig]).config(["$translateProvider",translateProviderConfig]).filter("bytes",bytesFilter).filter("noHTML",noHTMLFilter).filter("newlines",["$sce",newlinesFilter]).controller("TeraCLOUDShareCtrl",["$scope","$translate","$http",
"ngDialog","$location","$timeout","$sce",TeraCLOUDShareCtrl]);function exceptionHandlerFactory(a){return function(d,g){a.error(d,g);document.getElementById("mainHtml").setAttribute("hidden","");document.getElementById("errorHtml").removeAttribute("hidden")}}function ngDialogProviderConfig(a){a.setDefaults({className:"ngdialog-theme-default ds-editor-dialog ds-pt2",showClose:!0,closeByDocument:!1,closeByEscape:!0,width:"100%",height:"100%"})}function locationProviderConfig(a){a.html5Mode(!0)}
function httpProviderConfig(a){a.defaults.withCredentials=!0}
function translateProviderConfig(a){a.registerAvailableLanguageKeys(["en","ja"],{"en_*":"en","ja_*":"ja","*":"en"});a.determinePreferredLanguage();a.useMissingTranslationHandlerLog();a.useSanitizeValueStrategy("escaped");a.translations("en",{LoginConfirmPhrases:{shared_TeraCLOUD:"This file is shared from InfiniCLOUD.",login:"Login",no_account:"Don't have an account?",account_creation:"Sign Up",register_msg:"Registration only takes a minute! Get started now!",without_login:"Proceed to download",sharedFolder_TeraCLOUD:"This folder is shared from InfiniCLOUD."},
MainPhrases:{emphasis_symbol_left:'"',emphasis_symbol_right:'"',is_download:" will be downloaded.",keyword:"Access phrase",apply:"Send",file:"File name",size:"Size",update_time:"Last updated",download:"Download",shared_id_error:"Shared objects don't exist. Please confirm that the URL is correct.",open_folder:" will be shown.",folder:"Folder name",open:"Show"},KeywordPhrases:{required:"Please enter the access phrase.",checking:"Verifying access phrase...",incorrect:"Access phrase invalid. Please try entering the access phrase again.",
failure:"Failed to verify access phrase. Please wait a bit and try again."},DownloadPhrases:{begin:"Your download will begin shortly.",failure:"Download failed. Please reload the page and try again.",deleted:"File does not exist.",unexpected:"An unknown error occurred. Please wait a bit and try again."},OpenFolderPhrases:{begin:"The folder will be shown in a moment.",failure:"The folder could not be shown. Please reload the page.",deleted:"The folder does not exist."}});a.translations("ja",{LoginConfirmPhrases:{shared_TeraCLOUD:"\u3053\u306e\u30d5\u30a1\u30a4\u30eb\u306fInfiniCLOUD\u3067\u5171\u6709\u3055\u308c\u3066\u3044\u307e\u3059\u3002",
login:"\u30ed\u30b0\u30a4\u30f3",account_creation:"\u30a2\u30ab\u30a6\u30f3\u30c8\u767b\u9332",no_account:"\u30a2\u30ab\u30a6\u30f3\u30c8\u3092\u304a\u6301\u3061\u3067\u306f\u306a\u3044\u65b9\u306f",register_msg:"1\u5206\u3067\u7c21\u5358\u767b\u9332\uff01\u4eca\u3059\u3050\u30b9\u30bf\u30fc\u30c8\uff01",without_login:"\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u306b\u9032\u3080",sharedFolder_TeraCLOUD:"\u3053\u306e\u30d5\u30a9\u30eb\u30c0\u30fc\u306fInfiniCLOUD\u3067\u5171\u6709\u3055\u308c\u3066\u3044\u307e\u3059\u3002"},
MainPhrases:{emphasis_symbol_left:"\u300c",emphasis_symbol_right:"\u300d",is_download:"\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3057\u307e\u3059\u3002",keyword:"\u5408\u8a00\u8449",apply:"\u9001\u4fe1",file:"\u30d5\u30a1\u30a4\u30eb\u540d",size:"\u30b5\u30a4\u30ba",update_time:"\u66f4\u65b0\u65e5\u6642",download:"\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9",shared_id_error:"\u5171\u6709\u5bfe\u8c61\u304c\u5b58\u5728\u3057\u307e\u305b\u3093\u3002URL\u306b\u8aa4\u308a\u304c\u306a\u3044\u304b\u3054\u78ba\u8a8d\u304f\u3060\u3055\u3044\u3002",
open_folder:"\u30d5\u30a9\u30eb\u30c0\u30fc\u3092\u8868\u793a\u3057\u307e\u3059\u3002",folder:"\u30d5\u30a9\u30eb\u30c0\u30fc\u540d",open:"\u8868\u793a"},KeywordPhrases:{checking:"\u78ba\u8a8d\u4e2d\u2026",required:"\u5408\u8a00\u8449\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002",incorrect:"\u5408\u8a00\u8449\u304c\u9055\u3044\u307e\u3059\u3002\u3082\u3046\u4e00\u5ea6\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002",failure:"\u5408\u8a00\u8449\u306e\u78ba\u8a8d\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\u3057\u3070\u3089\u304f\u6642\u9593\u3092\u304a\u3044\u3066\u518d\u5ea6\u304a\u8a66\u3057\u304f\u3060\u3055\u3044\u3002"},
DownloadPhrases:{begin:"\u307e\u3082\u306a\u304f\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u304c\u958b\u59cb\u3055\u308c\u307e\u3059\u3002",failure:"\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u304c\u5931\u6557\u3057\u307e\u3057\u305f\u3002\u518d\u8aad\u307f\u8fbc\u307f\u3057\u3066\u304f\u3060\u3055\u3044\u3002",deleted:"\u30d5\u30a1\u30a4\u30eb\u304c\u5b58\u5728\u3057\u307e\u305b\u3093\u3002",unexpected:"\u4e0d\u660e\u306a\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\u3057\u3070\u3089\u304f\u6642\u9593\u3092\u304a\u3044\u3066\u304b\u3089\u518d\u5ea6\u304a\u8a66\u3057\u304f\u3060\u3055\u3044\u3002"},
OpenFolderPhrases:{begin:"\u307e\u3082\u306a\u304f\u30d5\u30a9\u30eb\u30c0\u30fc\u304c\u8868\u793a\u3055\u308c\u307e\u3059\u3002",failure:"\u30d5\u30a9\u30eb\u30c0\u30fc\u8868\u793a\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\u518d\u8aad\u307f\u8fbc\u307f\u3057\u3066\u304f\u3060\u3055\u3044\u3002",deleted:"\u30d5\u30a9\u30eb\u30c0\u30fc\u304c\u5b58\u5728\u3057\u307e\u305b\u3093\u3002"}})}
function bytesFilter(){return function(a,d){if(0===a)return"0 bytes";if(isNaN(parseFloat(a))||!isFinite(a))return"-";"undefined"===typeof d&&(d=1);var g=Math.floor(Math.log(a)/Math.log(1024));a=(a/Math.pow(1024,Math.floor(g))).toFixed(d);return(a.match(/\.0*$/)?a.substr(0,a.indexOf(".")):a)+" "+"B KB MB GB TB PB".split(" ")[g]}}function noHTMLFilter(){return function(a){return null===a||void 0===a?a:a.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;")}}
function newlinesFilter(a){return function(d){return null===d||void 0===d?d:a.trustAsHtml(d.replace(/\n/g,"<br />"))}}
function TeraCLOUDShareCtrl(a,d,g,p,n,D,A){function K(){var h=n.url().substr(1);""===h?(h=getCache("SHARE_KEY"),removeCache("SHARE_KEY"),null!==h&&n.url(h)):(h=h.match(/^([0-9a-f]{16})(\?.*)?$/),h=null===h?null:h[1]);return h}function F(h){h=g({method:"GET",url:a.SHARE_URL,headers:{Accept:"application/json",keyword:encodeURIComponent(void 0===h?"":h)},timeout:API_TIMEOUT_MSEC});h.then(function(q){a.sharedInfo=q.data},function(q){});return h}function L(){var h=g({method:"HEAD",url:a.API_OAUTH_PATH+
"notify;api_key=d7a4e811db6f067864b38aac65646210",timeout:API_TIMEOUT_MSEC});h.then(function(q){a.isShareId=!0},function(q){});return h}function N(){var h=g({method:"GET",url:api_host+"/v2/api/user/id;api_key=d7a4e811db6f067864b38aac65646210",timeout:API_TIMEOUT_MSEC});h.then(function(q){a.account_id=q.data.user},function(q){a.account_id=""});return h}function Q(){a.shareId=K();a.SHARE_URL="/v2/api/share/public/"+a.shareId;if(null===a.shareId)a.isShareId=!1;else{if("undefined"!==typeof API_HOST)h=
API_HOST;else{h=window.location.host.split(".");h[0]="api";var h=h.join(".");h=window.location.protocol+"//"+h}a.API_OAUTH_PATH=h+"/v2/api/oauth2/";a.TERACLOUD_TOP=TERACLOUD_TOPS[I];a.TERACLOUD_MYPAGE=a.TERACLOUD_TOP+"modules/teracloudsso/autologin";a.ACCOUNT_PATH=ACCOUNT;a.sharedInfo=null;a.account_id=null;F().then(function(q){a.aclType=a.sharedInfo.acl_type;a.isFolder=a.sharedInfo.content_type===RESOURCETYPE_FOLDER;q="LoginConfirmPhrases.";a.isFolder?(a.toDoPhrases=d.instant("MainPhrases.open_folder"),
a.contentsTypePhrases=d.instant("MainPhrases.folder"),a.toDoButtonPhrases=d.instant("MainPhrases.open"),q+="sharedFolder_TeraCLOUD"):(a.toDoPhrases=d.instant("MainPhrases.is_download"),a.contentsTypePhrases=d.instant("MainPhrases.file"),a.toDoButtonPhrases=d.instant("MainPhrases.download"),q+="shared_TeraCLOUD");a.sharedMessage=d.instant(q);L().then(function(m){N().then(null,function(E){})},function(m){p.open({template:"login_confirm",scope:a,onOpenCallback:function(){a.isShareId=!0;a.account_id=
""}})})},function(q){a.isShareId=!1})}}var I=d.use();a.aclType="default";a.isShareId="default";a.message="";a.dlMessageState="default";a.dlMessage=A.trustAsHtml("&nbsp");var B="";a.moveLoginPage=function(){setCache("SHARE_KEY",a.shareId);window.location.href=a.API_OAUTH_PATH+"top"};a.message_clear=function(){a.message=""};a.getSharedInfoWithKeyword=function(h){if(void 0!==h){a.message=d.instant("KeywordPhrases.checking");B="";var q=h.length;4>q||32<q?D(function(){a.message=d.instant("KeywordPhrases.incorrect")},
500):F(h).then(function(m){0===a.sharedInfo.keyword_valid?(a.aclType=0,B=h):a.message=d.instant("KeywordPhrases.incorrect")},function(m){a.message=d.instant("KeywordPhrases.failure")})}};a.getSharedContents=function(){a.dlMessageState="begin";if(a.isFolder){var h=d.instant("OpenFolderPhrases.begin");var q=d.instant("OpenFolderPhrases.failure");var m="OpenFolderPhrases.deleted"}else h=d.instant("DownloadPhrases.begin"),q=d.instant("DownloadPhrases.failure"),m="DownloadPhrases.deleted";var E=d.instant(m);
a.dlMessage=A.trustAsHtml(h);g({method:"POST",url:a.SHARE_URL,headers:{Accept:"application/json",keyword:encodeURIComponent(B),"Content-Type":"application/x-www-form-urlencoded"},data:"",timeout:API_TIMEOUT_MSEC}).then(function(u){window.location.href=u.data.location;D(function(){a.dlMessageState="default";a.dlMessage=A.trustAsHtml("&nbsp")},500)},function(u){a.dlMessageState="error";u=u.status;a.dlMessage=401==u?A.trustAsHtml(q):404==u?A.trustAsHtml(E):A.trustAsHtml(d.instant("DownloadPhrases.unexpected"))})};
a.initialize=function(){var h="/browser/js/site_config.js?"+(new Date).getTime();g({method:"GET",url:h,timeout:API_TIMEOUT_MSEC}).then(function(q){eval(q.data.replace(/var /g,""));Q()},function(q){-1===q.status&&"error"===q.xhrStatus&&window.location.reload()})}};function setPersistenceRaw(a,d){localStorage.setItem(a,d)}function getPersistenceRaw(a){return localStorage.getItem(a)}function setPersistence(a,d){setPersistenceRaw(a,JSON.stringify(d))}function getPersistence(a){a=getPersistenceRaw(a);return JSON.parse(a)}function removePersistence(a){localStorage.removeItem(a)}function setCacheRaw(a,d){sessionStorage.setItem(a,d)}function getCacheRaw(a){return sessionStorage.getItem(a)}function setCache(a,d){setCacheRaw(a,JSON.stringify(d))}
function getCache(a){a=getCacheRaw(a);return JSON.parse(a)}function removeCache(a){sessionStorage.removeItem(a)};/*
 ng-dialog - v1.2.0 (https://github.com/likeastore/ngDialog) */
!function(a,d){"undefined"!=typeof module&&module.exports?(d("undefined"==typeof angular?require("angular"):angular),module.exports="ngDialog"):"function"==typeof define&&define.amd?define(["angular"],d):d(a.angular)}(this,function(a){var d=a.module("ngDialog",[]),g=a.element,p=a.isDefined,n=(document.body||document.documentElement).style,D=p(n.animation)||p(n.WebkitAnimation)||p(n.MozAnimation)||p(n.MsAnimation)||p(n.OAnimation),A={html:!1,body:!1},K={},F=[],L=[],N=!1,Q=!1,I=[];return d.provider("ngDialog",
function(){var B=this.defaults={className:"ngdialog-theme-default",appendClassName:"",disableAnimation:!1,plain:!1,showClose:!0,closeByDocument:!0,closeByEscape:!0,closeByNavigation:!1,appendTo:!1,preCloseCallback:!1,onOpenCallback:!1,overlay:!0,cache:!0,trapFocus:!0,preserveFocus:!0,ariaAuto:!0,ariaRole:null,ariaLabelledById:null,ariaLabelledBySelector:null,ariaDescribedById:null,ariaDescribedBySelector:null,bodyClassName:"ngdialog-open",width:null,height:null};this.setForceHtmlReload=function(u){A.html=
u||!1};this.setForceBodyReload=function(u){A.body=u||!1};this.setDefaults=function(u){a.extend(B,u)};this.setOpenOnePerName=function(u){Q=u||!1};var h,q=0,m=0,E={};this.$get=["$document","$templateCache","$compile","$q","$http","$rootScope","$timeout","$window","$controller","$injector",function(u,V,W,R,X,z,Y,O,Z,P){var w=[],k={onDocumentKeydown:function(b){27===b.keyCode&&J.close("$escape")},activate:function(b){b.data("$ngDialogOptions").trapFocus&&(b.on("keydown",k.onTrapFocusKeydown),w.body.on("keydown",
k.onTrapFocusKeydown))},deactivate:function(b){b.off("keydown",k.onTrapFocusKeydown);w.body.off("keydown",k.onTrapFocusKeydown)},deactivateAll:function(b){a.forEach(b,function(c){c=a.element(c);k.deactivate(c)})},setBodyPadding:function(b){var c=parseInt(w.body.css("padding-right")||0,10);w.body.css("padding-right",c+b+"px");w.body.data("ng-dialog-original-padding",c);z.$broadcast("ngDialog.setPadding",b)},resetBodyPadding:function(){var b=w.body.data("ng-dialog-original-padding");b?w.body.css("padding-right",
b+"px"):w.body.css("padding-right","");z.$broadcast("ngDialog.setPadding",0)},performCloseDialog:function(b,c){var f=b.data("$ngDialogOptions"),l=b.attr("id"),e=K[l];if(k.deactivate(b),e){if("undefined"!=typeof O.Hammer){var C=e.hammerTime;C.off("tap",h);C.destroy&&C.destroy();delete e.hammerTime}else b.unbind("click");1===m&&w.body.unbind("keydown",k.onDocumentKeydown);b.hasClass("ngdialog-closing")||--m;(C=b.data("$ngDialogPreviousFocus"))&&C.focus&&C.focus();z.$broadcast("ngDialog.closing",b,c);
m=0>m?0:m;D&&!f.disableAnimation?(e.$destroy(),b.unbind("animationend webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend").bind("animationend webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend",function(){k.closeDialogElement(b,c)}).addClass("ngdialog-closing")):(e.$destroy(),k.closeDialogElement(b,c));E[l]&&(E[l].resolve({id:l,value:c,$dialog:b,remainingDialogs:m}),delete E[l]);K[l]&&delete K[l];F.splice(F.indexOf(l),1);F.length||(w.body.unbind("keydown",k.onDocumentKeydown),
N=!1);0==m&&(h=void 0)}},closeDialogElement:function(b,c){var f=b.data("$ngDialogOptions");b.remove();L.splice(L.indexOf(f.bodyClassName),1);-1===L.indexOf(f.bodyClassName)&&(w.html.removeClass(f.bodyClassName),w.body.removeClass(f.bodyClassName));0===m&&k.resetBodyPadding();z.$broadcast("ngDialog.closed",b,c)},closeDialog:function(b,c){var f=b.data("$ngDialogPreCloseCallback");if(f&&a.isFunction(f))if(f=f.call(b,c),a.isObject(f))f.closePromise?f.closePromise.then(function(){k.performCloseDialog(b,
c)},function(){return!1}):f.then(function(){k.performCloseDialog(b,c)},function(){return!1});else{if(!1===f)return!1;k.performCloseDialog(b,c)}else k.performCloseDialog(b,c)},onTrapFocusKeydown:function(b){var c=a.element(b.currentTarget);if(c.hasClass("ngdialog"))var f=c;else if(f=k.getActiveDialog(),null===f)return;c=!0===b.shiftKey;9===b.keyCode&&k.handleTab(f,b,c)},handleTab:function(b,c,f){b=k.getFocusableElements(b);if(0===b.length)return void(document.activeElement&&document.activeElement.blur&&
document.activeElement.blur());var l=Array.prototype.indexOf.call(b,document.activeElement),e=-1===l,C=l===b.length-1,v=!1;f?(e||0===l)&&(b[b.length-1].focus(),v=!0):(e||C)&&(b[0].focus(),v=!0);v&&(c.preventDefault(),c.stopPropagation())},autoFocus:function(b){var c=b[0],f=c.querySelector("*[autofocus]");if(null===f||(f.focus(),document.activeElement!==f)){b=k.getFocusableElements(b);if(0<b.length)return void b[0].focus();c=k.filterVisibleElements(c.querySelectorAll("h1,h2,h3,h4,h5,h6,p,span"));0<
c.length&&(c=c[0],g(c).attr("tabindex","-1").css("outline","0"),c.focus())}},getFocusableElements:function(b){b=b[0].querySelectorAll("a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, *[tabindex], *[contenteditable]");b=k.filterTabbableElements(b);return k.filterVisibleElements(b)},filterTabbableElements:function(b){for(var c=[],f=0;f<b.length;f++){var l=b[f];"-1"!==g(l).attr("tabindex")&&c.push(l)}return c},
filterVisibleElements:function(b){for(var c=[],f=0;f<b.length;f++){var l=b[f];(0<l.offsetWidth||0<l.offsetHeight)&&c.push(l)}return c},getActiveDialog:function(){var b=document.querySelectorAll(".ngdialog");return 0===b.length?null:g(b[b.length-1])},applyAriaAttributes:function(b,c){if(c.ariaAuto){if(!c.ariaRole){var f=0<k.getFocusableElements(b).length?"dialog":"alertdialog";c.ariaRole=f}c.ariaLabelledBySelector||(c.ariaLabelledBySelector="h1,h2,h3,h4,h5,h6");c.ariaDescribedBySelector||(c.ariaDescribedBySelector=
"article,section,p")}c.ariaRole&&b.attr("role",c.ariaRole);k.applyAriaAttribute(b,"aria-labelledby",c.ariaLabelledById,c.ariaLabelledBySelector);k.applyAriaAttribute(b,"aria-describedby",c.ariaDescribedById,c.ariaDescribedBySelector)},applyAriaAttribute:function(b,c,f,l){if(f)return void b.attr(c,f);if(l&&(f=b.attr("id"),l=b[0].querySelector(l)))return f=f+"-"+c,g(l).attr("id",f),b.attr(c,f),f},detectUIRouter:function(){return P.has("$transitions")?"1.0.0+":!!P.has("$state")&&"legacy"},getRouterLocationEventName:function(){return k.detectUIRouter()?
"$stateChangeStart":"$locationChangeStart"}},J={__PRIVATE__:k,open:function(b){function c(x,y){y=y||{};return y.headers=y.headers||{},a.extend(y.headers,{Accept:"text/html"}),z.$broadcast("ngDialog.templateLoading",x),X.get(x,y).then(function(G){return z.$broadcast("ngDialog.templateLoaded",x),G.data||""})}function f(x){return x?a.isString(x)&&e.plain?x:"boolean"!=typeof e.cache||e.cache?c(x,{cache:V}):c(x,{cache:!1}):"Empty template"}var l=null;if(b=b||{},!(Q&&b.name&&(l=b.name.toLowerCase().replace(/\s/g,
"-")+"-dialog",this.isOpen(l)))){var e=a.copy(B),C=++q;l=l||"ngdialog"+C;F.push(l);"undefined"!=typeof e.data&&("undefined"==typeof b.data&&(b.data={}),b.data=a.merge(a.copy(e.data),b.data));a.extend(e,b);E[l]=b=R.defer();var v;K[l]=v=a.isObject(e.scope)?e.scope.$new():z.$new();var r,T,M,S=a.extend({},e.resolve);return a.forEach(S,function(x,y){S[y]=a.isString(x)?P.get(x):P.invoke(x,null,null,y)}),R.all({template:f(e.template||e.templateUrl),locals:R.all(S)}).then(function(x){var y=x.template;x=x.locals;
e.showClose&&(y+='<button aria-label="Dismiss" class="ngdialog-close"></button>');(r=g('<div id="'+l+'" class="ngdialog'+(e.overlay?"":" ngdialog-no-overlay")+'"></div>'),r.html(e.overlay?'<div class="ngdialog-overlay"></div><div class="ngdialog-content" role="document">'+y+"</div>":'<div class="ngdialog-content" role="document">'+y+"</div>"),r.data("$ngDialogOptions",e),v.ngDialogId=l,e.data&&a.isString(e.data))?(y=e.data.replace(/^\s*/,"")[0],v.ngDialogData="{"===y||"["===y?a.fromJson(e.data):new String(e.data),
v.ngDialogData.ngDialogId=l):e.data&&a.isObject(e.data)&&(v.ngDialogData=e.data,v.ngDialogData.ngDialogId=l);if(e.className&&r.addClass(e.className),e.appendClassName&&r.addClass(e.appendClassName),e.width&&(M=r[0].querySelector(".ngdialog-content"),a.isString(e.width)?M.style.width=e.width:M.style.width=e.width+"px"),e.height&&(M=r[0].querySelector(".ngdialog-content"),a.isString(e.height)?M.style.height=e.height:M.style.height=e.height+"px"),e.disableAnimation&&r.addClass("ngdialog-disabled-animation"),
T=e.appendTo&&a.isString(e.appendTo)?a.element(document.querySelector(e.appendTo)):w.body,k.applyAriaAttributes(r,e),[{name:"$ngDialogPreCloseCallback",value:e.preCloseCallback},{name:"$ngDialogOnOpenCallback",value:e.onOpenCallback}].forEach(function(t){if(t.value){var H;a.isFunction(t.value)?H=t.value:a.isString(t.value)&&v&&(a.isFunction(v[t.value])?H=v[t.value]:v.$parent&&a.isFunction(v.$parent[t.value])?H=v.$parent[t.value]:z&&a.isFunction(z[t.value])&&(H=z[t.value]));H&&r.data(t.name,H)}}),
v.closeThisDialog=function(t){k.closeDialog(r,t)},e.controller&&(a.isString(e.controller)||a.isArray(e.controller)||a.isFunction(e.controller))){var G;e.controllerAs&&a.isString(e.controllerAs)&&(G=e.controllerAs);G=Z(e.controller,a.extend(x,{$scope:v,$element:r}),!0,G);e.bindToController&&a.extend(G.instance,{ngDialogId:v.ngDialogId,ngDialogData:v.ngDialogData,closeThisDialog:v.closeThisDialog,confirm:v.confirm});"function"==typeof G?r.data("$ngDialogControllerController",G()):r.data("$ngDialogControllerController",
G)}if(Y(function(){var t=document.querySelectorAll(".ngdialog");k.deactivateAll(t);W(r)(v);t=O.innerWidth-w.body.prop("clientWidth");w.html.addClass(e.bodyClassName);w.body.addClass(e.bodyClassName);L.push(e.bodyClassName);t-=O.innerWidth-w.body.prop("clientWidth");0<t&&k.setBodyPadding(t);T.append(r);k.activate(r);e.trapFocus&&k.autoFocus(r);e.name?z.$broadcast("ngDialog.opened",{dialog:r,name:e.name}):z.$broadcast("ngDialog.opened",r);(t=r.data("$ngDialogOnOpenCallback"))&&a.isFunction(t)&&t.call(r)}),
N||(w.body.bind("keydown",k.onDocumentKeydown),N=!0),e.closeByNavigation&&I.push(r),e.preserveFocus&&r.data("$ngDialogPreviousFocus",document.activeElement),h=function(t){var H=!!e.closeByDocument&&g(t.target).hasClass("ngdialog-overlay");t=g(t.target).hasClass("ngdialog-close");(H||t)&&J.close(r.attr("id"),t?"$closeButton":"$document")},"undefined"!=typeof O.Hammer)(v.hammerTime=O.Hammer(r[0])).on("tap",h);else r.bind("click",h);return m+=1,J}),{id:l,closePromise:b.promise,close:function(x){k.closeDialog(r,
x)}}}},openConfirm:function(b){var c=R.defer(),f=a.copy(B);b=b||{};"undefined"!=typeof f.data&&("undefined"==typeof b.data&&(b.data={}),b.data=a.merge(a.copy(f.data),b.data));a.extend(f,b);f.scope=a.isObject(f.scope)?f.scope.$new():z.$new();f.scope.confirm=function(e){c.resolve(e);var C=g(document.getElementById(l.id));k.performCloseDialog(C,e)};var l=J.open(f);if(l)return l.closePromise.then(function(e){return e?c.reject(e.value):c.reject()}),c.promise},isOpen:function(b){return 0<g(document.getElementById(b)).length},
close:function(b,c){var f=g(document.getElementById(b));f.length?k.closeDialog(f,c):"$escape"===b?(f=g(document.getElementById(F[F.length-1])),f.data("$ngDialogOptions").closeByEscape&&k.closeDialog(f,"$escape")):J.closeAll(c);return J},closeAll:function(b){for(var c=document.querySelectorAll(".ngdialog"),f=c.length-1;0<=f;f--)k.closeDialog(g(c[f]),b)},getOpenDialogs:function(){return F},getDefaults:function(){return B}};a.forEach(["html","body"],function(b){if(w[b]=u.find(b),A[b]){var c=k.getRouterLocationEventName();
z.$on(c,function(){w[b]=u.find(b)})}});var U=k.detectUIRouter();if("1.0.0+"===U)P.get("$transitions").onStart({},function(b){for(;0<I.length;)if(b=I.pop(),!1===k.closeDialog(b))return!1});else z.$on("legacy"===U?"$stateChangeStart":"$locationChangeStart",function(b){for(;0<I.length;){var c=I.pop();!1===k.closeDialog(c)&&b.preventDefault()}});return J}]}),d.directive("ngDialog",["ngDialog",function(B){return{restrict:"A",scope:{ngDialogScope:"="},link:function(h,q,m){q.on("click",function(E){E.preventDefault();
E=a.isDefined(h.ngDialogScope)?h.ngDialogScope:"noScope";a.isDefined(m.ngDialogClosePrevious)&&B.close(m.ngDialogClosePrevious);var u=B.getDefaults();B.open({template:m.ngDialog,className:m.ngDialogClass||u.className,appendClassName:m.ngDialogAppendClass,controller:m.ngDialogController,controllerAs:m.ngDialogControllerAs,bindToController:m.ngDialogBindToController,disableAnimation:m.ngDialogDisableAnimation,scope:E,data:m.ngDialogData,showClose:"false"!==m.ngDialogShowClose&&("true"===m.ngDialogShowClose||
u.showClose),closeByDocument:"false"!==m.ngDialogCloseByDocument&&("true"===m.ngDialogCloseByDocument||u.closeByDocument),closeByEscape:"false"!==m.ngDialogCloseByEscape&&("true"===m.ngDialogCloseByEscape||u.closeByEscape),overlay:"false"!==m.ngDialogOverlay&&("true"===m.ngDialogOverlay||u.overlay),preCloseCallback:m.ngDialogPreCloseCallback||u.preCloseCallback,onOpenCallback:m.ngDialogOnOpenCallback||u.onOpenCallback,bodyClassName:m.ngDialogBodyClass||u.bodyClassName})})}}}]),d});
